name: Continuous Integration

on:
  push:
    branches:
      - feature/**
      - release/**
      - hotfix/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: mvn clean package
      - name: Tests execution
        run: mvn test